# Generated by Django 4.2.25 on 2025-11-24 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('sku', models.CharField(db_index=True, max_length=50, verbose_name='SKU (رقم المنتج)')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='الكمية في المخزون')),
                ('unit_of_measure', models.CharField(help_text='مثال: قطعة، كجم، لتر', max_length=50, verbose_name='وحدة القياس')),
                ('reorder_level', models.PositiveIntegerField(default=10, verbose_name='حد إعادة الطلب')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'historical المنتج',
                'verbose_name_plural': 'historical المنتجات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
