# Generated by Django 4.2.25 on 2025-12-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'التقرير',
                'verbose_name_plural': 'التقارير',
                'permissions': [('view_report', 'Can view financial and operational reports')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
