# Generated by Django 4.2.25 on 2025-12-29 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الحساب')),
                ('account_type', models.CharField(choices=[('ASSET', 'أصول'), ('LIABILITY', 'التزامات'), ('EQUITY', 'حقوق ملكية'), ('REVENUE', 'إيرادات'), ('EXPENSE', 'مصروفات')], max_length=10, verbose_name='نوع الحساب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'شجرة الحسابات',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(verbose_name='الوصف / البيان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤه بواسطة')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='دائن')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='الحساب')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.journalentry', verbose_name='قيد اليومية')),
            ],
            options={
                'verbose_name': 'حركة محاسبية',
                'verbose_name_plural': 'الحركات المحاسبية',
            },
        ),
    ]
